## Lab 2

### Variant 9

### Task 1:
Виконати набір вправ. Всі завдання виконати 2 способами: 
- а) з використанням універсальних функцій бібліотеки NumPy. 
- b) за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо).
- с) для обох випадків підрахувати час виконання скрипту та
зробити висновки.

Exersizes: 1, 2, 4, 7, 8, 12, 15, 16, 20

Встановимо значення змінних та обʼявляємо допоміжні функції для виконання завдань:

In [2]:
import numpy as np

def eprint(numpy_f, iter_f):
    '''print with format for exersizes'''
    print("numpy:")
    print(numpy_f())
    %timeit -n 1000 numpy_f() 

    print("\niter:")
    print(iter_f())
    %timeit -n 1000 iter_f() 

# n = int(input("Enter a number: "))
n = 50
m = 100

#### Exersize 1:

Вводиться число n. Вивести масив розміру n×n, в якому по діагоналі йдуть числа від 1 до n, а інші числа дорівнюють 0.

In [26]:
# _n - stands for numpy implementation
# _i - stands for iterational/comprehensional implementation

def ex1n():
    return np.diag(range(1, n + 1))

def ex1i():
    ls = [[(i + 1 if i == j else 0) for i  in range(n)] for j in range(n)]
    return np.array(ls, dtype=np.int32)

eprint(ex1n, ex1i)


numpy:
[[ 1  0  0 ...  0  0  0]
 [ 0  2  0 ...  0  0  0]
 [ 0  0  3 ...  0  0  0]
 ...
 [ 0  0  0 ... 48  0  0]
 [ 0  0  0 ...  0 49  0]
 [ 0  0  0 ...  0  0 50]]
4.75 µs ± 989 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

iter:
[[ 1  0  0 ...  0  0  0]
 [ 0  2  0 ...  0  0  0]
 [ 0  0  3 ...  0  0  0]
 ...
 [ 0  0  0 ... 48  0  0]
 [ 0  0  0 ...  0 49  0]
 [ 0  0  0 ...  0  0 50]]
123 µs ± 840 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


Як бачимо з замірів часу, створення масиву з використанням універсальних функцій бібліотеки NumPy займає значно менше часу, ніж створення масиву за допомогою спискових виразів.

#### Exersize 2:

Вводиться число n. Розставити 1 та 0 у шаховому порядку, починаючи з 1 в матриці розміром n×n, використовуючи слайсінг.

In [4]:
def ex2n():
    res = np.zeros((n, n), dtype=np.int32)
    res[::2, ::2] = 1
    res[1::2, 1::2] = 1
    return res

def ex2i():
    ls = [[(1 if i % 2 == j % 2 else 0) for i in range(n)] for j in range(n)]
    return np.array(ls, dtype=np.int32)

eprint(ex2n, ex2i)

numpy:
[[1 0 1 ... 0 1 0]
 [0 1 0 ... 1 0 1]
 [1 0 1 ... 0 1 0]
 ...
 [0 1 0 ... 1 0 1]
 [1 0 1 ... 0 1 0]
 [0 1 0 ... 1 0 1]]
1.71 µs ± 442 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

iter:
[[1 0 1 ... 0 1 0]
 [0 1 0 ... 1 0 1]
 [1 0 1 ... 0 1 0]
 ...
 [0 1 0 ... 1 0 1]
 [1 0 1 ... 0 1 0]
 [0 1 0 ... 1 0 1]]
158 µs ± 1.08 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


Спискові вирази набагато повільніші за вбудовані функції numpy.

#### Exersize 4:

Вводяться числа n і m. Вивести масив розміру n×m, в якому у першому рядку (рядок з нулевим індексом) йдуть числа від 0 до m–1, а всі інші елементи матриці дорівнюють 0.

In [5]:
def ex4n():
    res = np.zeros((n, m), dtype=np.int32)
    res[0] = np.arange(m)
    return res
    

def ex4i():
    return np.array([[0 if i != 0 else j for j in range(m)] for i in range(n)])

eprint(ex4n, ex4i)

numpy:
[[ 0  1  2 ... 97 98 99]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
1.17 µs ± 264 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

iter:
[[ 0  1  2 ... 97 98 99]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
256 µs ± 1.98 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


Спискові вирази набагато повільніші за вбудовані функції numpy.

#### Exersize 7:

З клавіатури вводиться масив. Замінити всі нульові елементи на –1.

In [6]:
# arr_n = [int(x) for x in input("Enter array: ").split()]

arr_n = np.random.randint(0, 10, n)
arr_i = arr_n.copy()

def ex7n():
    arr_n[arr_n == 0] = -1
    return arr_n

def ex7i():
    for i in range(n):
        if arr_i[i] == 0:
            arr_i[i] = -1
    return arr_i

eprint(ex7n, ex7i)

numpy:
[-1  3  8  4  2  8  7  7  8  2  4  5  9  2  4  1  8  8  4  3  6  1  3  2
  2  7  3  3  7  7  7  8  9  6  4  6  5  5  6  4  5  1  1  8  3 -1  4  5
  9  3]
618 ns ± 11.1 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

iter:
[-1  3  8  4  2  8  7  7  8  2  4  5  9  2  4  1  8  8  4  3  6  1  3  2
  2  7  3  3  7  7  7  8  9  6  4  6  5  5  6  4  5  1  1  8  3 -1  4  5
  9  3]
3.17 µs ± 95.9 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


Оскільки в цій вправі ми не створюєм масив списковим виразом, а лише міняємо необхідні елементи,

а також тому що складність лінійна - різниця в часі виконання між використанням універсальних функцій бібліотеки NumPy та спискових виразів менша ніж у попередніх вправах.

#### Exersize 8:
З клавіатури вводиться масив. Підрахувати в ньому кількість нульових та ненульових елементів.

In [27]:
# arr_n = [int(x) for x in input("Enter array: ").split()]

arr_n = np.random.randint(0, 10, n)
arr_i = arr_n.copy()

def ex8n():
    zerro_len = len(arr_n[arr_n == 0])
    return zerro_len, len(arr_n) - zerro_len

def ex8i():
    zerro_len = len([i for i in arr_i if i == 0])
    return zerro_len, len(arr_n) - zerro_len

eprint(ex8n, ex8i)

numpy:
(3, 47)
815 ns ± 51.8 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

iter:
(3, 47)
2.44 µs ± 121 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


Оскільки в цій вправі ми не створюєм масив списковим виразом, а лише міняємо необхідні елементи,

а також тому що складність лінійна - різниця в часі виконання між використанням універсальних функцій бібліотеки NumPy та спискових виразів менша 

ніж у вправах, де використовувалися двовимірні спискові вирази.

#### Exersize 12:

Створити масив одиниць розміром n×n та створити в ньому «рамку», що утворюється з 0.

In [8]:
def ex12n():
    res = np.ones((n, n), dtype=np.int32)
    res[0, :] = 0
    res[-1, :] = 0
    res[:, 0] = 0
    res[:, -1] = 0
    
    return res

def ex12i():
    res = np.ones((n, n), dtype=np.int32)
    for i in range(n):
        res[0, i] = 0
        res[-1, i] = 0
        res[i, 0] = 0
        res[i, -1] = 0
    return res

eprint(ex12n, ex12i)

numpy:
[[0 0 0 ... 0 0 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 0 0 ... 0 0 0]]
2.33 µs ± 669 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

iter:
[[0 0 0 ... 0 0 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 0 0 ... 0 0 0]]
14.2 µs ± 503 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


Оскільки в цій вправі ми не створюєм масив списковим виразом, а лише міняємо необхідні елементи,

а також тому що складність лінійна - різниця в часі виконання між використанням універсальних функцій бібліотеки NumPy та спискових виразів менша 

ніж у вправах, де використовувалися двовимірні спискові вирази.

#### Exersize 15:

Заповнити парні стовпчикі матриці розміром n×n одиницями, а непарні – нулями.

In [9]:
def ex15n():
    res = np.zeros((n, n), dtype=np.int32)
    res[:, 1::2] = 1
    return res

def ex15i():
    res = np.zeros((n, n), dtype=np.int32)
    for i in range(n):
        for j in range(1, n, 2):
            res[i, j] = 1
    return res

eprint(ex15n, ex15i)


numpy:
[[0 1 0 ... 1 0 1]
 [0 1 0 ... 1 0 1]
 [0 1 0 ... 1 0 1]
 ...
 [0 1 0 ... 1 0 1]
 [0 1 0 ... 1 0 1]
 [0 1 0 ... 1 0 1]]
1.21 µs ± 190 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

iter:
[[0 1 0 ... 1 0 1]
 [0 1 0 ... 1 0 1]
 [0 1 0 ... 1 0 1]
 ...
 [0 1 0 ... 1 0 1]
 [0 1 0 ... 1 0 1]
 [0 1 0 ... 1 0 1]]
82.5 µs ± 536 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


В даній вправі складність квадратична, тому різниця в часі виконатння більша ніж у вправах з лінійною складністю.

#### Exersize 16:

Заповнити вектор значеннями від 0 до n. Всі значення, що більші за n/4 та менші за 3n/4 замінити нулями.

In [10]:
def ex16n():
    res = np.arange(0, n)
    res[res > n/4] = 0
    res[res < 3*n/4] = 0
    return res

def ex16i():
    res = np.array([0 if i > n/4 or i < 3*n/4 else i for i in range(n)])
    return res

eprint(ex16n, ex16i)

numpy:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]
2.51 µs ± 808 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

iter:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]
4.2 µs ± 96.3 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


В даній вправі наймерша різниця в часі виконання між використанням універсальних функцій бібліотеки NumPy та спискових виразів.

Ймовірно це повʼязано з неефективною реалізацією масок в бібліотеці NumPy.

#### Exersize 20:

Згенерувати вектор із n випадкових елементів, що лежать в інтервалі (0,1). Замінити максимальний елемент на 0.

In [11]:
def ex20n():
    res = np.random.randint(0, 2, n)
    res[res.argmax()] = 0
    return res

def ex20i():
    res = np.random.randint(0, 2, n)
    max_i = 0
    for i in range(n):
        if res[i] > res[max_i]:
            max_i = i
            
    res[max_i] = 0
    return res

eprint(ex20n, ex20i)

numpy:
[0 0 1 1 1 0 1 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 1 1 0 0 0 1 1 0 0 1 1 1 0 1
 1 1 1 1 0 0 0 1 1 1 0 0 1]
3.38 µs ± 181 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

iter:
[0 0 0 1 0 1 1 0 1 0 1 0 0 1 1 0 1 0 1 0 0 0 0 1 1 0 1 0 1 0 0 1 0 0 1 0 0
 1 0 0 0 0 0 1 0 1 0 0 0 1]
8.04 µs ± 32.9 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


В даній вправі теж одна з найменших різниць в часі виконання. Але все ще MyPy ефективніше щонайменше в 2 рази. 

### Task 2:

Розв’язати систему алгебраїчних рівнянь за допомогою
формул Крамера і виконати перевірку за допомогою:
- a) матричного множення;
- b) оберненої матриці;
- c) функції numpy.linalg.solve().

Порівняти всі рішення за допомогою функції numpy.allclose().

$
\begin{cases}
  x_1 + 2x_2 + x_3 + x_4 = 8, \\
  2x_1 + x_2 + x_3 + x_4 = 5, \\
  x_1 - x_2 + 2x_3 + x_4 = -1, \\
  x_1 + x_2 - x_3 + 3x_4 = 10, \\
\end{cases}
$

Визначимо задану систему рівнянь:

In [12]:
A = np.array([[1, 2, 1, 1],
              [2, 1, 1, 1],
              [1, -1, 2, 1],
              [1, 1, -1, 3]])

b = np.array([8, 5, -1, 10])

#### Розв'яжемо систему за допомогою формул Крамера (правило Крамера):

In [13]:
def cramer_rule(A, b):
    det_A = np.linalg.det(A)
    if det_A == 0:
        raise ValueError("Cramer's rule is not applicable")
    else:
        n = A.shape[0]
        x = np.zeros(n)
        for i in range(n):
            A_temp = A.copy()
            A_temp[:, i] = b
            x[i] = np.linalg.det(A_temp) / det_A
        return x

In [14]:
x_cramer = cramer_rule(A, b)
print(x_cramer)
%timeit -n 1000 cramer_rule(A, b)

[-0.05263158  2.94736842 -0.15789474  2.31578947]
14.2 µs ± 1.98 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


#### a) Виконаємо перевірку за допомогою **матричного множення**:

In [15]:
A_x = np.dot(A, x_cramer)
print("\nA * x_cramer: ", A_x)
%timeit -n 1000 np.dot(A, x_cramer)

print("\nnp.allclose(A_x, b): ",  np.allclose(A_x, b))


A * x_cramer:  [ 8.  5. -1. 10.]
954 ns ± 451 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

np.allclose(A_x, b):  True


#### a) Виконаємо перевірку за допомогою **оберненої матриці**:

In [16]:
A_inv = np.linalg.inv(A)
print("A_inv:\n", A_inv)
%timeit -n 1000 np.linalg.inv(A)
x_inv = np.dot(A_inv, b)
print("\nA_inv * b:", x_inv)
%timeit -n 1000 np.dot(A_inv, b)

print("\np.allclose(x_cramer, x_inv): ", np.allclose(x_cramer, x_inv))

A_inv:
 [[-0.52631579  0.89473684 -0.21052632 -0.05263158]
 [ 0.47368421 -0.10526316 -0.21052632 -0.05263158]
 [ 0.42105263 -0.31578947  0.36842105 -0.15789474]
 [ 0.15789474 -0.36842105  0.26315789  0.31578947]]
5.34 µs ± 1.2 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

A_inv * b: [-0.05263158  2.94736842 -0.15789474  2.31578947]
1.31 µs ± 357 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

p.allclose(x_cramer, x_inv):  True


#### a) Виконаємо перевірку за допомогою **функції numpy.linalg.solve()**:

In [17]:
x_solve = np.linalg.solve(A, b)
print("\nnp.linalg.solve():", x_solve)
%timeit -n 1000 np.linalg.solve(A, b)

print("\nnp.allclose(x_cramer, x_solve): ", np.allclose(x_cramer, x_solve))


np.linalg.solve(): [-0.05263158  2.94736842 -0.15789474  2.31578947]
4.11 µs ± 866 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

np.allclose(x_cramer, x_solve):  True


### Task 3:
Обчислити значення матричного виразу
- а) з використанням універсальних функцій бібліотеки NumPy.
- b) за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо).
- с) для обох випадків підрахувати час виконання скрипту та зробити висновок.

Порівняти всі рішення за допомогою функції numpy.allclose().

$
2A - (A^2 + B) B 
$

A = $ \begin{pmatrix}
  1 & 4 & 2 \\
  2 & 1 & -2 \\
  0 & 1 & -1 \\
\end{pmatrix} $, 
B = $ \begin{pmatrix}
  4 & 6 & -2 \\
  4 & 10 & 1 \\
  2 & 4 & -5 \\
\end{pmatrix} $

Визначимо задані матриці: 

In [18]:
A = np.array([[1, 4, 2],
              [2, 1, -2],
              [0, 1, -1]])

B = np.array([[4, 6, -2],
              [4, 10, 1],
              [2, 4, -5]])

#### a) Обчислимо значення матричного виразу з використанням **універсальних функцій бібліотеки NumPy**: 

In [19]:
num_res = 2 * A - ((A @ A) + B) @ B
print("NumPy result:\n", num_res)

NumPy result:
 [[ -94 -190  -36]
 [-106 -236   20]
 [ -20  -38  -28]]


#### b) Напишемо свої операції для обчислення матричного виразу:

In [20]:
def dot(A, B):
    if A.shape[1] != B.shape[0]:
        raise ValueError("The number of columns in matrix A must be equal to the number of rows in matrix B for multiplication.")
    
    result = np.zeros_like(A)
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            for k in range(A.shape[1]):
                result[i][j] += A[i][k] * B[k][j]
    return result

def add(A, B):
    if A.shape != B.shape:
        raise ValueError("Matrices must have the same shape for addition.")
        
    result = np.zeros_like(A)
    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            result[i][j] = A[i][j] + B[i][j]
    return result

def sdot(scalar, matrix):
    result = np.zeros_like(matrix)
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            result[i][j] = scalar * matrix[i][j]
    return result

Обчислимо значення матричного виразу:

In [21]:
A_squared = dot(A, A)
A_squared_plus_B = add(A_squared, B)
it_res = sdot(2, A) - dot(A_squared_plus_B, B)

print(it_res)

[[ -94 -190  -36]
 [-106 -236   20]
 [ -20  -38  -28]]


#### c) Для обох випадків підрахуємо **час виконання** скрипту та зробимо висновок.

In [22]:
%%timeit -n 1000 

num_res = 2 * A - ((A @ A) + B) @ B

2.32 µs ± 123 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [23]:
%%timeit -n 1000
A_squared = dot(A, A)
A_squared_plus_B = add(A_squared, B)
it_res = sdot(2, A) - dot(A_squared_plus_B, B)

39.8 µs ± 2.95 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


##### Висновок:

Вбудовані матричні операції швидше власноруч написаних в ~16.32 раз, оскільки написані на мові програмування C.

#### d) Порівняємо всі рішення за допомогою функції **numpy.allclose()**.

In [24]:
print("\nNumPy result == Iterative result:", np.allclose(num_res, it_res))


NumPy result == Iterative result: True
