In [68]:
import numpy as np
import pandas as pd

df = pd.read_csv('./data/Expanded_data_with_more_features.csv')

df

Unnamed: 0  Gender EthnicGroup          ParentEduc     LunchType  \
0               0  female         NaN   bachelor's degree      standard   
1               1  female     group C        some college      standard   
2               2  female     group B     master's degree      standard   
3               3    male     group A  associate's degree  free/reduced   
4               4    male     group C        some college      standard   
...           ...     ...         ...                 ...           ...   
30636         816  female     group D         high school      standard   
30637         890    male     group E         high school      standard   
30638         911  female         NaN         high school  free/reduced   
30639         934  female     group D  associate's degree      standard   
30640         960    male     group B        some college      standard   

        TestPrep ParentMaritalStatus PracticeSport IsFirstChild  NrSiblings  \
0           none             married     regularly          yes         3.0   
1            NaN             married     sometimes          yes         0.0   
2           none              single     sometimes          yes         4.0   
3           none             married         never           no         1.0   
4           none             married     sometimes          yes         0.0   
...          ...                 ...           ...          ...         ...   
30636       none              single     sometimes           no         2.0   
30637       none              single     regularly           no         1.0   
30638  completed             married     sometimes           no         1.0   
30639  completed             married     regularly           no         3.0   
30640       none             married         never           no         1.0   

      TransportMeans WklyStudyHours  MathScore  ReadingScore  WritingScore  
0         school_bus            < 5         71            71            74  
1                NaN         5 - 10         69            90            88  
2         school_bus            < 5         87            93            91  
3                NaN         5 - 10         45            56            42  
4         school_bus         5 - 10         76            78            75  
...              ...            ...        ...           ...           ...  
30636     school_bus         5 - 10         59            61            65  
30637        private         5 - 10         58            53            51  
30638        private         5 - 10         61            70            67  
30639     school_bus         5 - 10         82            90            93  
30640     school_bus         5 - 10         64            60            58  

[30641 rows x 15 columns]

# Аналіз набору даних за допомогою Pandas, NumPy, візуалізації даних за допомогою Matplotlib у блокноті Jupyter.

## Завдання 1 (15 балів)
Students Exam Scores: Extended Dataset | Kaggle

https://www.kaggle.com/datasets/desalegngeb/students-exam-scores

### Проаналізуйте розподіл за статтю серед учнів.
1. Скільки студентів і студенток у наборі даних?

In [69]:
students_cnt = len(df)
students_cnt

30641

2. Який відсоток студентів чоловічої статі в наборі даних?

In [70]:
male_perc = len(df[df['Gender'] == 'male']) / students_cnt * 100
male_perc

49.6622172905584

3. Який відсоток студенток у наборі даних?

In [71]:
female_perc = len(df[df['Gender'] == 'female']) / students_cnt * 100
female_perc

50.337782709441605

### Дослідіть зв’язок між етнічною групою та результатами тестів.
4. Яка етнічна група має найвищий середній бал з математики?

In [72]:
df.groupby('EthnicGroup')['MathScore'].mean().idxmax()

'group E'

5. Яка етнічна група має найвищий середній бал читання

In [73]:
df.groupby('EthnicGroup')['ReadingScore'].mean().idxmax()

'group E'

6. Яка етнічна група має найвищий середній бал з письма?

In [74]:
df.groupby('EthnicGroup')['WritingScore'].mean().idxmax()

'group E'

### Дослідіть вплив курсу підготовки до тесту на результати тесту.
7. Який середній бал з математики для студентів, які закінчили курс підготовки до тесту?

In [75]:
df.groupby('TestPrep')['MathScore'].mean()['completed']

69.5466599698644

8. Який середній бал з читання для студентів, які пройшли курс підготовки до тесту?

In [76]:
df.groupby('TestPrep')['MathScore'].mean()['completed']

69.5466599698644

9. Який середній бал для студентів, які закінчили курс підготовки до тесту?

In [77]:
df.groupby('TestPrep').agg({'MathScore': 'mean', 'ReadingScore': 'mean', 'WritingScore': 'mean'}).loc['completed'].mean()

72.66097438473129

### Проаналізуйте розподіл батьків(ів) за сімейним станом серед учнів.
10. Скільки студентів мають одружених батьків?

In [78]:
len(df[df['ParentMaritalStatus'] == 'married'])

16844

11. Скільки студентів мають батьків-одинаків?

In [79]:
len(df[df['ParentMaritalStatus'] == 'single'])

7097

### Дослідіть зв’язок між заняттями спортом і результатами тестів.
12. Чи студенти, які регулярно займаються спортом, мають вищі середні результати з математики, ніж ті','хто ніколи не займається спортом?

In [80]:
math_sport = df.groupby('PracticeSport')['MathScore'].mean()

math_sport['never'] < math_sport['sometimes'] < math_sport['regularly']

True

13. Чи студенти','які регулярно займаються спортом','мають вищі середні результати читання','ніж ті, хто ніколи не займається спортом?

In [81]:
reading_sport = df.groupby('PracticeSport')['MathScore'].mean()

reading_sport['never'] < reading_sport['sometimes'] < reading_sport['regularly']

True

### Проаналізуйте розподіл транспортних засобів до школи серед учнів.
14. Скільки учнів користується шкільним автобусом, щоб дістатися до школи?

In [82]:
len(df[df['TransportMeans'] == 'school_bus'])

16145

15. Скільки учнів користується приватним транспортом, щоб дістатися до школи?

In [83]:
len(df[df['TransportMeans'] == 'private'])

11362

## Задача 2: класифікація (5 балів)
Передбачте, чи завершив студент курс підготовки до іспиту, на основі його демографічних та академічних даних.
Вхідні дані:

Gender, EthnicGroup, ParentEduc, LunchType, ParentMaritalStatus, PracticeSport, IsFirstChild, NrSiblings, TransportMeans, WklyStudyHours, MathScore, ReadingScore, WritingScore
   Результат: TestPrep

In [100]:
import tensorflow as tf

# Prepare the data
selected = df[[
    'Gender','EthnicGroup','ParentEduc','LunchType','ParentMaritalStatus',
    'PracticeSport','IsFirstChild','NrSiblings','TransportMeans','WklyStudyHours',
    'MathScore','ReadingScore','WritingScore', 'TestPrep'
]]

test_data = selected.sample(frac=0.2, random_state=0)
train_data = selected.drop(test_data.index)

x_train = pd.get_dummies(train_data.drop('TestPrep', axis=1)).to_numpy()
y_train = train_data['TestPrep'].apply(lambda x: 1 if x == 'completed' else 0).to_numpy()

columns_count = x_train.shape[1]

print(x_train.shape)
print(x_train)
print(y_train.shape)
print(y_train)

model = tf.keras.models.Sequential([
    tf.keras.layers.Input(shape=(columns_count,)),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(1)
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(x_train, y_train, epochs=100, batch_size=32)

model.predict(x_train[0])

(24513, 33)
[[ 3. 71. 71. ...  0.  1.  0.]
 [ 0. 69. 90. ...  1.  0.  0.]
 [ 4. 87. 93. ...  0.  1.  0.]
 ...
 [ 2. 59. 61. ...  1.  0.  0.]
 [ 1. 61. 70. ...  1.  0.  0.]
 [ 3. 82. 90. ...  1.  0.  0.]]
(24513,)
[0 0 0 ... 0 1 1]
Epoch 1/100
767/767 [==============================] - 1s 627us/step - loss: nan - accuracy: 0.6744
Epoch 2/100
767/767 [==============================] - 0s 568us/step - loss: nan - accuracy: 0.6748
Epoch 3/100
767/767 [==============================] - 0s 516us/step - loss: nan - accuracy: 0.6748
Epoch 4/100
767/767 [==============================] - 0s 496us/step - loss: nan - accuracy: 0.6748
Epoch 5/100
767/767 [==============================] - 0s 492us/step - loss: nan - accuracy: 0.6748
Epoch 6/100
767/767 [==============================] - 0s 515us/step - loss: nan - accuracy: 0.6748
Epoch 7/100
767/767 [==============================] - 0s 546us/step - loss: nan - accuracy: 0.6748
Epoch 8/100
767/767 [==============================] - 0s 489us/step 

KeyboardInterrupt: 